// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: indexstore.proto

package indexstore

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FieldDesc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id            uint64                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Container     string                 `protobuf:"bytes,3,opt,name=container,proto3" json:"container,omitempty"` // "default", "ac", "range", etc.
	Parser        string                 `protobuf:"bytes,4,opt,name=parser,proto3" json:"parser,omitempty"`       // e.g. "identity", "number", "str_hash"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldDesc) Reset() {
	*x = FieldDesc{}
	mi := &file_indexstore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldDesc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldDesc) ProtoMessage() {}

func (x *FieldDesc) ProtoReflect() protoreflect.Message {
	mi := &file_indexstore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldDesc.ProtoReflect.Descriptor instead.
func (*FieldDesc) Descriptor() ([]byte, []int) {
	return file_indexstore_proto_rawDescGZIP(), []int{0}
}

func (x *FieldDesc) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FieldDesc) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FieldDesc) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *FieldDesc) GetParser() string {
	if x != nil {
		return x.Parser
	}
	return ""
}

type IndexMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int32                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	IndexerType   string                 `protobuf:"bytes,2,opt,name=indexer_type,json=indexerType,proto3" json:"indexer_type,omitempty"` // "kgroups" or "compact"
	Fields        map[string]*FieldDesc  `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	IdAllocator   map[string]uint64      `protobuf:"bytes,4,rep,name=id_allocator,json=idAllocator,proto3" json:"id_allocator,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // string key -> internal ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexMetadata) Reset() {
	*x = IndexMetadata{}
	mi := &file_indexstore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexMetadata) ProtoMessage() {}

func (x *IndexMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_indexstore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexMetadata.ProtoReflect.Descriptor instead.
func (*IndexMetadata) Descriptor() ([]byte, []int) {
	return file_indexstore_proto_rawDescGZIP(), []int{1}
}

func (x *IndexMetadata) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *IndexMetadata) GetIndexerType() string {
	if x != nil {
		return x.IndexerType
	}
	return ""
}

func (x *IndexMetadata) GetFields() map[string]*FieldDesc {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *IndexMetadata) GetIdAllocator() map[string]uint64 {
	if x != nil {
		return x.IdAllocator
	}
	return nil
}

type EntryIDList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []uint64               `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntryIDList) Reset() {
	*x = EntryIDList{}
	mi := &file_indexstore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntryIDList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryIDList) ProtoMessage() {}

func (x *EntryIDList) ProtoReflect() protoreflect.Message {
	mi := &file_indexstore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryIDList.ProtoReflect.Descriptor instead.
func (*EntryIDList) Descriptor() ([]byte, []int) {
	return file_indexstore_proto_rawDescGZIP(), []int{2}
}

func (x *EntryIDList) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type TermPostingEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Field uint64                 `protobuf:"varint,1,opt,name=field,proto3" json:"field,omitempty"`
	// Types that are valid to be assigned to FieldValue:
	//
	//	*TermPostingEntry_U64Val
	//	*TermPostingEntry_StrVal
	FieldValue    isTermPostingEntry_FieldValue `protobuf_oneof:"field_value"`
	Ids           *EntryIDList                  `protobuf:"bytes,4,opt,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TermPostingEntry) Reset() {
	*x = TermPostingEntry{}
	mi := &file_indexstore_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TermPostingEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TermPostingEntry) ProtoMessage() {}

func (x *TermPostingEntry) ProtoReflect() protoreflect.Message {
	mi := &file_indexstore_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TermPostingEntry.ProtoReflect.Descriptor instead.
func (*TermPostingEntry) Descriptor() ([]byte, []int) {
	return file_indexstore_proto_rawDescGZIP(), []int{3}
}

func (x *TermPostingEntry) GetField() uint64 {
	if x != nil {
		return x.Field
	}
	return 0
}

func (x *TermPostingEntry) GetFieldValue() isTermPostingEntry_FieldValue {
	if x != nil {
		return x.FieldValue
	}
	return nil
}

func (x *TermPostingEntry) GetU64Val() uint64 {
	if x != nil {
		if x, ok := x.FieldValue.(*TermPostingEntry_U64Val); ok {
			return x.U64Val
		}
	}
	return 0
}

func (x *TermPostingEntry) GetStrVal() string {
	if x != nil {
		if x, ok := x.FieldValue.(*TermPostingEntry_StrVal); ok {
			return x.StrVal
		}
	}
	return ""
}

func (x *TermPostingEntry) GetIds() *EntryIDList {
	if x != nil {
		return x.Ids
	}
	return nil
}

type isTermPostingEntry_FieldValue interface {
	isTermPostingEntry_FieldValue()
}

type TermPostingEntry_U64Val struct {
	U64Val uint64 `protobuf:"varint,2,opt,name=u64_val,json=u64Val,proto3,oneof"`
}

type TermPostingEntry_StrVal struct {
	StrVal string `protobuf:"bytes,3,opt,name=str_val,json=strVal,proto3,oneof"`
}

func (*TermPostingEntry_U64Val) isTermPostingEntry_FieldValue() {}

func (*TermPostingEntry_StrVal) isTermPostingEntry_FieldValue() {}

// CompressedFlatMap: Stores compressed(flat) map representation for (field_id, str_key) -> posting list.
// It avoids expanding posting lists into explicit ids during Dump/Load.
type FlatMapKey struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	FieldId uint64                 `protobuf:"varint,1,opt,name=field_id,json=fieldId,proto3" json:"field_id,omitempty"`
	StrKey  string                 `protobuf:"bytes,2,opt,name=str_key,json=strKey,proto3" json:"str_key,omitempty"`
	// Header offset (start index) in the Headers array.
	HeaderOffset uint32 `protobuf:"varint,3,opt,name=header_offset,json=headerOffset,proto3" json:"header_offset,omitempty"`
	// Total length of the posting list.
	Length        uint32 `protobuf:"varint,4,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlatMapKey) Reset() {
	*x = FlatMapKey{}
	mi := &file_indexstore_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlatMapKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlatMapKey) ProtoMessage() {}

func (x *FlatMapKey) ProtoReflect() protoreflect.Message {
	mi := &file_indexstore_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlatMapKey.ProtoReflect.Descriptor instead.
func (*FlatMapKey) Descriptor() ([]byte, []int) {
	return file_indexstore_proto_rawDescGZIP(), []int{4}
}

func (x *FlatMapKey) GetFieldId() uint64 {
	if x != nil {
		return x.FieldId
	}
	return 0
}

func (x *FlatMapKey) GetStrKey() string {
	if x != nil {
		return x.StrKey
	}
	return ""
}

func (x *FlatMapKey) GetHeaderOffset() uint32 {
	if x != nil {
		return x.HeaderOffset
	}
	return 0
}

func (x *FlatMapKey) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

type FlatMapHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastEntryId   uint64                 `protobuf:"varint,1,opt,name=last_entry_id,json=lastEntryId,proto3" json:"last_entry_id,omitempty"`
	Offset        uint32                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlatMapHeader) Reset() {
	*x = FlatMapHeader{}
	mi := &file_indexstore_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlatMapHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlatMapHeader) ProtoMessage() {}

func (x *FlatMapHeader) ProtoReflect() protoreflect.Message {
	mi := &file_indexstore_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlatMapHeader.ProtoReflect.Descriptor instead.
func (*FlatMapHeader) Descriptor() ([]byte, []int) {
	return file_indexstore_proto_rawDescGZIP(), []int{5}
}

func (x *FlatMapHeader) GetLastEntryId() uint64 {
	if x != nil {
		return x.LastEntryId
	}
	return 0
}

func (x *FlatMapHeader) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type CompressedFlatMap struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Block size used when compressing posting lists.
	BlockSize     uint32           `protobuf:"varint,1,opt,name=block_size,json=blockSize,proto3" json:"block_size,omitempty"`
	Keys          []*FlatMapKey    `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	Headers       []*FlatMapHeader `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty"`
	Data          []byte           `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompressedFlatMap) Reset() {
	*x = CompressedFlatMap{}
	mi := &file_indexstore_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompressedFlatMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompressedFlatMap) ProtoMessage() {}

func (x *CompressedFlatMap) ProtoReflect() protoreflect.Message {
	mi := &file_indexstore_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompressedFlatMap.ProtoReflect.Descriptor instead.
func (*CompressedFlatMap) Descriptor() ([]byte, []int) {
	return file_indexstore_proto_rawDescGZIP(), []int{6}
}

func (x *CompressedFlatMap) GetBlockSize() uint32 {
	if x != nil {
		return x.BlockSize
	}
	return 0
}

func (x *CompressedFlatMap) GetKeys() []*FlatMapKey {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *CompressedFlatMap) GetHeaders() []*FlatMapHeader {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *CompressedFlatMap) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// ACEntriesHolder: Stores keyword -> entries mapping
type ACEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Ids           *EntryIDList           `protobuf:"bytes,2,opt,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ACEntry) Reset() {
	*x = ACEntry{}
	mi := &file_indexstore_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ACEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ACEntry) ProtoMessage() {}

func (x *ACEntry) ProtoReflect() protoreflect.Message {
	mi := &file_indexstore_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ACEntry.ProtoReflect.Descriptor instead.
func (*ACEntry) Descriptor() ([]byte, []int) {
	return file_indexstore_proto_rawDescGZIP(), []int{7}
}

func (x *ACEntry) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ACEntry) GetIds() *EntryIDList {
	if x != nil {
		return x.Ids
	}
	return nil
}

type ACHolderDump struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*ACEntry             `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ACHolderDump) Reset() {
	*x = ACHolderDump{}
	mi := &file_indexstore_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ACHolderDump) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ACHolderDump) ProtoMessage() {}

func (x *ACHolderDump) ProtoReflect() protoreflect.Message {
	mi := &file_indexstore_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ACHolderDump.ProtoReflect.Descriptor instead.
func (*ACHolderDump) Descriptor() ([]byte, []int) {
	return file_indexstore_proto_rawDescGZIP(), []int{8}
}

func (x *ACHolderDump) GetEntries() []*ACEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// RangeHolder / OptimizedRangeHolder: Stores precise matches + range definitions
type RangeEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Left  int64                  `protobuf:"varint,1,opt,name=left,proto3" json:"left,omitempty"`
	Right int64                  `protobuf:"varint,2,opt,name=right,proto3" json:"right,omitempty"`
	// uint64 entry_id = 3; // Deprecated
	Bitmap        []byte   `protobuf:"bytes,4,opt,name=bitmap,proto3" json:"bitmap,omitempty"`   // Serialized RoaringBitmap
	Ids           []uint64 `protobuf:"varint,5,rep,packed,name=ids,proto3" json:"ids,omitempty"` // Fallback list
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RangeEntry) Reset() {
	*x = RangeEntry{}
	mi := &file_indexstore_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeEntry) ProtoMessage() {}

func (x *RangeEntry) ProtoReflect() protoreflect.Message {
	mi := &file_indexstore_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeEntry.ProtoReflect.Descriptor instead.
func (*RangeEntry) Descriptor() ([]byte, []int) {
	return file_indexstore_proto_rawDescGZIP(), []int{9}
}

func (x *RangeEntry) GetLeft() int64 {
	if x != nil {
		return x.Left
	}
	return 0
}

func (x *RangeEntry) GetRight() int64 {
	if x != nil {
		return x.Right
	}
	return 0
}

func (x *RangeEntry) GetBitmap() []byte {
	if x != nil {
		return x.Bitmap
	}
	return nil
}

func (x *RangeEntry) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

// CompressedInt64FlatMap: Stores compressed(flat) map representation for int64 -> posting list.
// Used by OptimizedRangeHolder for EQ postings.
type Int64FlatMapKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   int64                  `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	// Header offset (start index) in the Headers array.
	HeaderOffset uint32 `protobuf:"varint,2,opt,name=header_offset,json=headerOffset,proto3" json:"header_offset,omitempty"`
	// Total length of the posting list.
	Length        uint32 `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Int64FlatMapKey) Reset() {
	*x = Int64FlatMapKey{}
	mi := &file_indexstore_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Int64FlatMapKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int64FlatMapKey) ProtoMessage() {}

func (x *Int64FlatMapKey) ProtoReflect() protoreflect.Message {
	mi := &file_indexstore_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int64FlatMapKey.ProtoReflect.Descriptor instead.
func (*Int64FlatMapKey) Descriptor() ([]byte, []int) {
	return file_indexstore_proto_rawDescGZIP(), []int{10}
}

func (x *Int64FlatMapKey) GetKey() int64 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *Int64FlatMapKey) GetHeaderOffset() uint32 {
	if x != nil {
		return x.HeaderOffset
	}
	return 0
}

func (x *Int64FlatMapKey) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

type CompressedInt64FlatMap struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Block size used when compressing posting lists.
	BlockSize     uint32             `protobuf:"varint,1,opt,name=block_size,json=blockSize,proto3" json:"block_size,omitempty"`
	Keys          []*Int64FlatMapKey `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	Headers       []*FlatMapHeader   `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty"`
	Data          []byte             `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompressedInt64FlatMap) Reset() {
	*x = CompressedInt64FlatMap{}
	mi := &file_indexstore_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompressedInt64FlatMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompressedInt64FlatMap) ProtoMessage() {}

func (x *CompressedInt64FlatMap) ProtoReflect() protoreflect.Message {
	mi := &file_indexstore_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompressedInt64FlatMap.ProtoReflect.Descriptor instead.
func (*CompressedInt64FlatMap) Descriptor() ([]byte, []int) {
	return file_indexstore_proto_rawDescGZIP(), []int{11}
}

func (x *CompressedInt64FlatMap) GetBlockSize() uint32 {
	if x != nil {
		return x.BlockSize
	}
	return 0
}

func (x *CompressedInt64FlatMap) GetKeys() []*Int64FlatMapKey {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *CompressedInt64FlatMap) GetHeaders() []*FlatMapHeader {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *CompressedInt64FlatMap) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type RangeHolderDump struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Precise matches (e.g. age = 18)
	EqFlat *CompressedInt64FlatMap `protobuf:"bytes,1,opt,name=eq_flat,json=eqFlat,proto3" json:"eq_flat,omitempty"`
	// Range definitions (e.g. age in [10, 20])
	Ranges        []*RangeEntry `protobuf:"bytes,2,rep,name=ranges,proto3" json:"ranges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RangeHolderDump) Reset() {
	*x = RangeHolderDump{}
	mi := &file_indexstore_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeHolderDump) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeHolderDump) ProtoMessage() {}

func (x *RangeHolderDump) ProtoReflect() protoreflect.Message {
	mi := &file_indexstore_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeHolderDump.ProtoReflect.Descriptor instead.
func (*RangeHolderDump) Descriptor() ([]byte, []int) {
	return file_indexstore_proto_rawDescGZIP(), []int{12}
}

func (x *RangeHolderDump) GetEqFlat() *CompressedInt64FlatMap {
	if x != nil {
		return x.EqFlat
	}
	return nil
}

func (x *RangeHolderDump) GetRanges() []*RangeEntry {
	if x != nil {
		return x.Ranges
	}
	return nil
}

type TermDict struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 简单的 Block 存储：所有字符串拼接在一起
	Content []byte `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	// 偏移量列表
	Offsets []uint32 `protobuf:"varint,2,rep,packed,name=offsets,proto3" json:"offsets,omitempty"`
	// FST 数据 (预留)
	FstData       []byte `protobuf:"bytes,3,opt,name=fst_data,json=fstData,proto3" json:"fst_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TermDict) Reset() {
	*x = TermDict{}
	mi := &file_indexstore_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TermDict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TermDict) ProtoMessage() {}

func (x *TermDict) ProtoReflect() protoreflect.Message {
	mi := &file_indexstore_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TermDict.ProtoReflect.Descriptor instead.
func (*TermDict) Descriptor() ([]byte, []int) {
	return file_indexstore_proto_rawDescGZIP(), []int{13}
}

func (x *TermDict) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *TermDict) GetOffsets() []uint32 {
	if x != nil {
		return x.Offsets
	}
	return nil
}

func (x *TermDict) GetFstData() []byte {
	if x != nil {
		return x.FstData
	}
	return nil
}

type PostingPtr struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// uint64 term_id = 1; // 隐式使用数组下标
	HeaderOffset  uint32 `protobuf:"varint,2,opt,name=header_offset,json=headerOffset,proto3" json:"header_offset,omitempty"` // 指向 PostingData 的 Header 索引
	Length        uint32 `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`                                 // 包含的文档数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostingPtr) Reset() {
	*x = PostingPtr{}
	mi := &file_indexstore_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostingPtr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostingPtr) ProtoMessage() {}

func (x *PostingPtr) ProtoReflect() protoreflect.Message {
	mi := &file_indexstore_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostingPtr.ProtoReflect.Descriptor instead.
func (*PostingPtr) Descriptor() ([]byte, []int) {
	return file_indexstore_proto_rawDescGZIP(), []int{14}
}

func (x *PostingPtr) GetHeaderOffset() uint32 {
	if x != nil {
		return x.HeaderOffset
	}
	return 0
}

func (x *PostingPtr) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

type SegmentData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 1. Term Dictionary
	Dict *TermDict `protobuf:"bytes,1,opt,name=dict,proto3" json:"dict,omitempty"`
	// 2. Postings (Index 是 TermID)
	Postings []*PostingPtr `protobuf:"bytes,2,rep,name=postings,proto3" json:"postings,omitempty"`
	// 3. Compressed Posting Data (实际的倒排数据块)
	// 包含 Headers 和 Data
	// 注意：这里复用 FlatMapHeader 的概念，但不使用 CompressedFlatMap 结构
	Headers     []*FlatMapHeader `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty"`
	PostingData []byte           `protobuf:"bytes,4,opt,name=posting_data,json=postingData,proto3" json:"posting_data,omitempty"`
	// Block size used
	BlockSize     uint32 `protobuf:"varint,5,opt,name=block_size,json=blockSize,proto3" json:"block_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SegmentData) Reset() {
	*x = SegmentData{}
	mi := &file_indexstore_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SegmentData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentData) ProtoMessage() {}

func (x *SegmentData) ProtoReflect() protoreflect.Message {
	mi := &file_indexstore_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentData.ProtoReflect.Descriptor instead.
func (*SegmentData) Descriptor() ([]byte, []int) {
	return file_indexstore_proto_rawDescGZIP(), []int{15}
}

func (x *SegmentData) GetDict() *TermDict {
	if x != nil {
		return x.Dict
	}
	return nil
}

func (x *SegmentData) GetPostings() []*PostingPtr {
	if x != nil {
		return x.Postings
	}
	return nil
}

func (x *SegmentData) GetHeaders() []*FlatMapHeader {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *SegmentData) GetPostingData() []byte {
	if x != nil {
		return x.PostingData
	}
	return nil
}

func (x *SegmentData) GetBlockSize() uint32 {
	if x != nil {
		return x.BlockSize
	}
	return 0
}

// Represents a single field's serialized data
type HolderDump struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FieldName     string                 `protobuf:"bytes,1,opt,name=field_name,json=fieldName,proto3" json:"field_name,omitempty"`
	HolderType    string                 `protobuf:"bytes,2,opt,name=holder_type,json=holderType,proto3" json:"holder_type,omitempty"`
	Content       []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`                 // Serialized protobuf of specific holder (e.g. DefaultHolderDump)
	GroupId       int32                  `protobuf:"varint,4,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"` // For K-Groups: which container it belongs to
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HolderDump) Reset() {
	*x = HolderDump{}
	mi := &file_indexstore_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HolderDump) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HolderDump) ProtoMessage() {}

func (x *HolderDump) ProtoReflect() protoreflect.Message {
	mi := &file_indexstore_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HolderDump.ProtoReflect.Descriptor instead.
func (*HolderDump) Descriptor() ([]byte, []int) {
	return file_indexstore_proto_rawDescGZIP(), []int{16}
}

func (x *HolderDump) GetFieldName() string {
	if x != nil {
		return x.FieldName
	}
	return ""
}

func (x *HolderDump) GetHolderType() string {
	if x != nil {
		return x.HolderType
	}
	return ""
}

func (x *HolderDump) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *HolderDump) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

// Represents the whole index dump (if small enough to be loaded at once)
// For large indexes, we recommend streaming: Metadata -> Wildcards -> Repeated HolderDump
type IndexDump struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *IndexMetadata         `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Wildcards     *EntryIDList           `protobuf:"bytes,2,opt,name=wildcards,proto3" json:"wildcards,omitempty"`
	Holders       []*HolderDump          `protobuf:"bytes,3,rep,name=holders,proto3" json:"holders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexDump) Reset() {
	*x = IndexDump{}
	mi := &file_indexstore_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexDump) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexDump) ProtoMessage() {}

func (x *IndexDump) ProtoReflect() protoreflect.Message {
	mi := &file_indexstore_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexDump.ProtoReflect.Descriptor instead.
func (*IndexDump) Descriptor() ([]byte, []int) {
	return file_indexstore_proto_rawDescGZIP(), []int{17}
}

func (x *IndexDump) GetMetadata() *IndexMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *IndexDump) GetWildcards() *EntryIDList {
	if x != nil {
		return x.Wildcards
	}
	return nil
}

func (x *IndexDump) GetHolders() []*HolderDump {
	if x != nil {
		return x.Holders
	}
	return nil
}

var File_indexstore_proto protoreflect.FileDescriptor

const file_indexstore_proto_rawDesc = "" +
	"\n" +
	"\x10indexstore.proto\x12\n" +
	"indexstore\"e\n" +
	"\tFieldDesc\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x04R\x02id\x12\x1c\n" +
	"\tcontainer\x18\x03 \x01(\tR\tcontainer\x12\x16\n" +
	"\x06parser\x18\x04 \x01(\tR\x06parser\"\xec\x02\n" +
	"\rIndexMetadata\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x05R\aversion\x12!\n" +
	"\findexer_type\x18\x02 \x01(\tR\vindexerType\x12=\n" +
	"\x06fields\x18\x03 \x03(\v2%.indexstore.IndexMetadata.FieldsEntryR\x06fields\x12M\n" +
	"\fid_allocator\x18\x04 \x03(\v2*.indexstore.IndexMetadata.IdAllocatorEntryR\vidAllocator\x1aP\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.indexstore.FieldDescR\x05value:\x028\x01\x1a>\n" +
	"\x10IdAllocatorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"\x1f\n" +
	"\vEntryIDList\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x04R\x03ids\"\x98\x01\n" +
	"\x10TermPostingEntry\x12\x14\n" +
	"\x05field\x18\x01 \x01(\x04R\x05field\x12\x19\n" +
	"\au64_val\x18\x02 \x01(\x04H\x00R\x06u64Val\x12\x19\n" +
	"\astr_val\x18\x03 \x01(\tH\x00R\x06strVal\x12)\n" +
	"\x03ids\x18\x04 \x01(\v2\x17.indexstore.EntryIDListR\x03idsB\r\n" +
	"\vfield_value\"}\n" +
	"\n" +
	"FlatMapKey\x12\x19\n" +
	"\bfield_id\x18\x01 \x01(\x04R\afieldId\x12\x17\n" +
	"\astr_key\x18\x02 \x01(\tR\x06strKey\x12#\n" +
	"\rheader_offset\x18\x03 \x01(\rR\fheaderOffset\x12\x16\n" +
	"\x06length\x18\x04 \x01(\rR\x06length\"K\n" +
	"\rFlatMapHeader\x12\"\n" +
	"\rlast_entry_id\x18\x01 \x01(\x04R\vlastEntryId\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\rR\x06offset\"\xa7\x01\n" +
	"\x11CompressedFlatMap\x12\x1d\n" +
	"\n" +
	"block_size\x18\x01 \x01(\rR\tblockSize\x12*\n" +
	"\x04keys\x18\x02 \x03(\v2\x16.indexstore.FlatMapKeyR\x04keys\x123\n" +
	"\aheaders\x18\x03 \x03(\v2\x19.indexstore.FlatMapHeaderR\aheaders\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"N\n" +
	"\aACEntry\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12)\n" +
	"\x03ids\x18\x02 \x01(\v2\x17.indexstore.EntryIDListR\x03ids\"=\n" +
	"\fACHolderDump\x12-\n" +
	"\aentries\x18\x01 \x03(\v2\x13.indexstore.ACEntryR\aentries\"`\n" +
	"\n" +
	"RangeEntry\x12\x12\n" +
	"\x04left\x18\x01 \x01(\x03R\x04left\x12\x14\n" +
	"\x05right\x18\x02 \x01(\x03R\x05right\x12\x16\n" +
	"\x06bitmap\x18\x04 \x01(\fR\x06bitmap\x12\x10\n" +
	"\x03ids\x18\x05 \x03(\x04R\x03ids\"`\n" +
	"\x0fInt64FlatMapKey\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12#\n" +
	"\rheader_offset\x18\x02 \x01(\rR\fheaderOffset\x12\x16\n" +
	"\x06length\x18\x03 \x01(\rR\x06length\"\xb1\x01\n" +
	"\x16CompressedInt64FlatMap\x12\x1d\n" +
	"\n" +
	"block_size\x18\x01 \x01(\rR\tblockSize\x12/\n" +
	"\x04keys\x18\x02 \x03(\v2\x1b.indexstore.Int64FlatMapKeyR\x04keys\x123\n" +
	"\aheaders\x18\x03 \x03(\v2\x19.indexstore.FlatMapHeaderR\aheaders\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"~\n" +
	"\x0fRangeHolderDump\x12;\n" +
	"\aeq_flat\x18\x01 \x01(\v2\".indexstore.CompressedInt64FlatMapR\x06eqFlat\x12.\n" +
	"\x06ranges\x18\x02 \x03(\v2\x16.indexstore.RangeEntryR\x06ranges\"Y\n" +
	"\bTermDict\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\x12\x18\n" +
	"\aoffsets\x18\x02 \x03(\rR\aoffsets\x12\x19\n" +
	"\bfst_data\x18\x03 \x01(\fR\afstData\"I\n" +
	"\n" +
	"PostingPtr\x12#\n" +
	"\rheader_offset\x18\x02 \x01(\rR\fheaderOffset\x12\x16\n" +
	"\x06length\x18\x03 \x01(\rR\x06length\"\xe2\x01\n" +
	"\vSegmentData\x12(\n" +
	"\x04dict\x18\x01 \x01(\v2\x14.indexstore.TermDictR\x04dict\x122\n" +
	"\bpostings\x18\x02 \x03(\v2\x16.indexstore.PostingPtrR\bpostings\x123\n" +
	"\aheaders\x18\x03 \x03(\v2\x19.indexstore.FlatMapHeaderR\aheaders\x12!\n" +
	"\fposting_data\x18\x04 \x01(\fR\vpostingData\x12\x1d\n" +
	"\n" +
	"block_size\x18\x05 \x01(\rR\tblockSize\"\x81\x01\n" +
	"\n" +
	"HolderDump\x12\x1d\n" +
	"\n" +
	"field_name\x18\x01 \x01(\tR\tfieldName\x12\x1f\n" +
	"\vholder_type\x18\x02 \x01(\tR\n" +
	"holderType\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\x12\x19\n" +
	"\bgroup_id\x18\x04 \x01(\x05R\agroupId\"\xab\x01\n" +
	"\tIndexDump\x125\n" +
	"\bmetadata\x18\x01 \x01(\v2\x19.indexstore.IndexMetadataR\bmetadata\x125\n" +
	"\twildcards\x18\x02 \x01(\v2\x17.indexstore.EntryIDListR\twildcards\x120\n" +
	"\aholders\x18\x03 \x03(\v2\x16.indexstore.HolderDumpR\aholdersB\x0eZ\f./indexstoreb\x06proto3"

var (
	file_indexstore_proto_rawDescOnce sync.Once
	file_indexstore_proto_rawDescData []byte
)

func file_indexstore_proto_rawDescGZIP() []byte {
	file_indexstore_proto_rawDescOnce.Do(func() {
		file_indexstore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_indexstore_proto_rawDesc), len(file_indexstore_proto_rawDesc)))
	})
	return file_indexstore_proto_rawDescData
}

var file_indexstore_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_indexstore_proto_goTypes = []any{
	(*FieldDesc)(nil),              // 0: indexstore.FieldDesc
	(*IndexMetadata)(nil),          // 1: indexstore.IndexMetadata
	(*EntryIDList)(nil),            // 2: indexstore.EntryIDList
	(*TermPostingEntry)(nil),       // 3: indexstore.TermPostingEntry
	(*FlatMapKey)(nil),             // 4: indexstore.FlatMapKey
	(*FlatMapHeader)(nil),          // 5: indexstore.FlatMapHeader
	(*CompressedFlatMap)(nil),      // 6: indexstore.CompressedFlatMap
	(*ACEntry)(nil),                // 7: indexstore.ACEntry
	(*ACHolderDump)(nil),           // 8: indexstore.ACHolderDump
	(*RangeEntry)(nil),             // 9: indexstore.RangeEntry
	(*Int64FlatMapKey)(nil),        // 10: indexstore.Int64FlatMapKey
	(*CompressedInt64FlatMap)(nil), // 11: indexstore.CompressedInt64FlatMap
	(*RangeHolderDump)(nil),        // 12: indexstore.RangeHolderDump
	(*TermDict)(nil),               // 13: indexstore.TermDict
	(*PostingPtr)(nil),             // 14: indexstore.PostingPtr
	(*SegmentData)(nil),            // 15: indexstore.SegmentData
	(*HolderDump)(nil),             // 16: indexstore.HolderDump
	(*IndexDump)(nil),              // 17: indexstore.IndexDump
	nil,                            // 18: indexstore.IndexMetadata.FieldsEntry
	nil,                            // 19: indexstore.IndexMetadata.IdAllocatorEntry
}
var file_indexstore_proto_depIdxs = []int32{
	18, // 0: indexstore.IndexMetadata.fields:type_name -> indexstore.IndexMetadata.FieldsEntry
	19, // 1: indexstore.IndexMetadata.id_allocator:type_name -> indexstore.IndexMetadata.IdAllocatorEntry
	2,  // 2: indexstore.TermPostingEntry.ids:type_name -> indexstore.EntryIDList
	4,  // 3: indexstore.CompressedFlatMap.keys:type_name -> indexstore.FlatMapKey
	5,  // 4: indexstore.CompressedFlatMap.headers:type_name -> indexstore.FlatMapHeader
	2,  // 5: indexstore.ACEntry.ids:type_name -> indexstore.EntryIDList
	7,  // 6: indexstore.ACHolderDump.entries:type_name -> indexstore.ACEntry
	10, // 7: indexstore.CompressedInt64FlatMap.keys:type_name -> indexstore.Int64FlatMapKey
	5,  // 8: indexstore.CompressedInt64FlatMap.headers:type_name -> indexstore.FlatMapHeader
	11, // 9: indexstore.RangeHolderDump.eq_flat:type_name -> indexstore.CompressedInt64FlatMap
	9,  // 10: indexstore.RangeHolderDump.ranges:type_name -> indexstore.RangeEntry
	13, // 11: indexstore.SegmentData.dict:type_name -> indexstore.TermDict
	14, // 12: indexstore.SegmentData.postings:type_name -> indexstore.PostingPtr
	5,  // 13: indexstore.SegmentData.headers:type_name -> indexstore.FlatMapHeader
	1,  // 14: indexstore.IndexDump.metadata:type_name -> indexstore.IndexMetadata
	2,  // 15: indexstore.IndexDump.wildcards:type_name -> indexstore.EntryIDList
	16, // 16: indexstore.IndexDump.holders:type_name -> indexstore.HolderDump
	0,  // 17: indexstore.IndexMetadata.FieldsEntry.value:type_name -> indexstore.FieldDesc
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_indexstore_proto_init() }
func file_indexstore_proto_init() {
	if File_indexstore_proto != nil {
		return
	}
	file_indexstore_proto_msgTypes[3].OneofWrappers = []any{
		(*TermPostingEntry_U64Val)(nil),
		(*TermPostingEntry_StrVal)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_indexstore_proto_rawDesc), len(file_indexstore_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_indexstore_proto_goTypes,
		DependencyIndexes: file_indexstore_proto_depIdxs,
		MessageInfos:      file_indexstore_proto_msgTypes,
	}.Build()
	File_indexstore_proto = out.File
	file_indexstore_proto_goTypes = nil
	file_indexstore_proto_depIdxs = nil
}
