// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: cache.proto

package cache

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FieldCache struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Eid           uint64                 `protobuf:"varint,1,opt,name=eid,proto3" json:"eid,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldCache) Reset() {
	*x = FieldCache{}
	mi := &file_cache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldCache) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldCache) ProtoMessage() {}

func (x *FieldCache) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldCache.ProtoReflect.Descriptor instead.
func (*FieldCache) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{0}
}

func (x *FieldCache) GetEid() uint64 {
	if x != nil {
		return x.Eid
	}
	return 0
}

func (x *FieldCache) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type IndexingTxCache struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConjunctionId uint64                 `protobuf:"varint,1,opt,name=conjunction_id,json=conjunctionId,proto3" json:"conjunction_id,omitempty"`
	FieldData     map[string]*FieldCache `protobuf:"bytes,2,rep,name=field_data,json=fieldData,proto3" json:"field_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexingTxCache) Reset() {
	*x = IndexingTxCache{}
	mi := &file_cache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexingTxCache) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexingTxCache) ProtoMessage() {}

func (x *IndexingTxCache) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexingTxCache.ProtoReflect.Descriptor instead.
func (*IndexingTxCache) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{1}
}

func (x *IndexingTxCache) GetConjunctionId() uint64 {
	if x != nil {
		return x.ConjunctionId
	}
	return 0
}

func (x *IndexingTxCache) GetFieldData() map[string]*FieldCache {
	if x != nil {
		return x.FieldData
	}
	return nil
}

type StrListValues struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StrListValues) Reset() {
	*x = StrListValues{}
	mi := &file_cache_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StrListValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrListValues) ProtoMessage() {}

func (x *StrListValues) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrListValues.ProtoReflect.Descriptor instead.
func (*StrListValues) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{2}
}

func (x *StrListValues) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type Int64ListValues struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []int64                `protobuf:"varint,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Int64ListValues) Reset() {
	*x = Int64ListValues{}
	mi := &file_cache_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Int64ListValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int64ListValues) ProtoMessage() {}

func (x *Int64ListValues) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int64ListValues.ProtoReflect.Descriptor instead.
func (*Int64ListValues) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{3}
}

func (x *Int64ListValues) GetValues() []int64 {
	if x != nil {
		return x.Values
	}
	return nil
}

type Uint64ListValues struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []uint64               `protobuf:"varint,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Uint64ListValues) Reset() {
	*x = Uint64ListValues{}
	mi := &file_cache_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Uint64ListValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Uint64ListValues) ProtoMessage() {}

func (x *Uint64ListValues) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Uint64ListValues.ProtoReflect.Descriptor instead.
func (*Uint64ListValues) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{4}
}

func (x *Uint64ListValues) GetValues() []uint64 {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_cache_proto protoreflect.FileDescriptor

const file_cache_proto_rawDesc = "" +
	"\n" +
	"\vcache.proto\x12\x05cache\"2\n" +
	"\n" +
	"FieldCache\x12\x10\n" +
	"\x03eid\x18\x01 \x01(\x04R\x03eid\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\xcf\x01\n" +
	"\x0fIndexingTxCache\x12%\n" +
	"\x0econjunction_id\x18\x01 \x01(\x04R\rconjunctionId\x12D\n" +
	"\n" +
	"field_data\x18\x02 \x03(\v2%.cache.IndexingTxCache.FieldDataEntryR\tfieldData\x1aO\n" +
	"\x0eFieldDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.cache.FieldCacheR\x05value:\x028\x01\"'\n" +
	"\rStrListValues\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\")\n" +
	"\x0fInt64ListValues\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x03R\x06values\"*\n" +
	"\x10Uint64ListValues\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x04R\x06valuesB\tZ\a./cacheb\x06proto3"

var (
	file_cache_proto_rawDescOnce sync.Once
	file_cache_proto_rawDescData []byte
)

func file_cache_proto_rawDescGZIP() []byte {
	file_cache_proto_rawDescOnce.Do(func() {
		file_cache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cache_proto_rawDesc), len(file_cache_proto_rawDesc)))
	})
	return file_cache_proto_rawDescData
}

var file_cache_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_cache_proto_goTypes = []any{
	(*FieldCache)(nil),       // 0: cache.FieldCache
	(*IndexingTxCache)(nil),  // 1: cache.IndexingTxCache
	(*StrListValues)(nil),    // 2: cache.StrListValues
	(*Int64ListValues)(nil),  // 3: cache.Int64ListValues
	(*Uint64ListValues)(nil), // 4: cache.Uint64ListValues
	nil,                      // 5: cache.IndexingTxCache.FieldDataEntry
}
var file_cache_proto_depIdxs = []int32{
	5, // 0: cache.IndexingTxCache.field_data:type_name -> cache.IndexingTxCache.FieldDataEntry
	0, // 1: cache.IndexingTxCache.FieldDataEntry.value:type_name -> cache.FieldCache
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_cache_proto_init() }
func file_cache_proto_init() {
	if File_cache_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cache_proto_rawDesc), len(file_cache_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cache_proto_goTypes,
		DependencyIndexes: file_cache_proto_depIdxs,
		MessageInfos:      file_cache_proto_msgTypes,
	}.Build()
	File_cache_proto = out.File
	file_cache_proto_goTypes = nil
	file_cache_proto_depIdxs = nil
}
